### ISSUE TITLE
Video recording function when running with agent testNG

### ISSUE THREAD

**Issue by namtrinh93267** [zebrunner/java-agent-testng#6]
Could I use video recording function? I've read the doc but only screenshot available.

**Comment by vdelendik** [comment]
@namtrinh93267, video recording should be organized on grid layer. Agent might registered standard and custom links to video recording via: https://zebrunner.com/documentation/reporting/carina-testng/#capturing-session-artifacts

to see how video recording works take a look to zebrunner pro: https://zebrunner.com or community edition: https://github.com/zebrunner/community-edition
